# Generated by Django 4.2.16 on 2025-02-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_acknowledgement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acknowledgement',
        ),
    ]
